from fpdf import FPDF
from core.optimizer import AllocationResult
from core.data_model import CampaignInput
from pathlib import Path
import urllib.request
import os


# ─────────────────────────────────────────
# FONT SETUP
# Download DejaVu font if not present.
# DejaVu supports all Unicode characters
# including —, ·, accented letters, Arabic.
# ─────────────────────────────────────────

FONT_DIR  = Path(__file__).parent.parent / "data" / "fonts"
FONT_REGULAR = FONT_DIR / "DejaVuSans.ttf"
FONT_BOLD    = FONT_DIR / "DejaVuSans-Bold.ttf"

FONT_URLS = {
    "DejaVuSans.ttf": (
        "https://github.com/dejavu-fonts/dejavu-fonts/raw/main/"
        "ttf/DejaVuSans.ttf"
    ),
    "DejaVuSans-Bold.ttf": (
        "https://github.com/dejavu-fonts/dejavu-fonts/raw/main/"
        "ttf/DejaVuSans-Bold.ttf"
    ),
}


def ensure_fonts():
    """Downloads DejaVu fonts if they don't exist locally."""
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for filename, url in FONT_URLS.items():
        path = FONT_DIR / filename
        if not path.exists():
            try:
                urllib.request.urlretrieve(url, path)
            except Exception as e:
                raise RuntimeError(
                    f"Could not download font {filename}: {e}. "
                    "Please download DejaVuSans.ttf and "
                    "DejaVuSans-Bold.ttf manually and place them in "
                    f"{FONT_DIR}"
                )


# ─────────────────────────────────────────
# PDF CLASS
# ─────────────────────────────────────────

class BudgetOptPDF(FPDF):

    def header(self):
        self.set_font("DejaVu", "B", 14)
        self.set_text_color(30, 30, 30)
        self.cell(
            0, 10,
            "BudgetOpt - Campaign Allocation Report",
            align="C", new_x="LMARGIN", new_y="NEXT",
        )
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "", 8)
        self.set_text_color(150, 150, 150)
        self.cell(
            0, 10,
            f"Generated by BudgetOpt | Page {self.page_no()}",
            align="C",
        )


# ─────────────────────────────────────────
# MAIN FUNCTION
# ─────────────────────────────────────────

def generate_pdf(
    campaign: CampaignInput,
    result:   AllocationResult,
) -> bytes:
    """
    Generates a PDF report and returns it as bytes.
    Uses DejaVu Unicode font to support all characters.
    """
    ensure_fonts()

    pdf = BudgetOptPDF()

    # Register DejaVu as a Unicode font
    pdf.add_font("DejaVu", "",  str(FONT_REGULAR))
    pdf.add_font("DejaVu", "B", str(FONT_BOLD))

    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Section 1: Campaign summary ───────────────────────
    pdf.set_font("DejaVu", "B", 12)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(
        0, 8, "1. Campaign Overview",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.set_draw_color(230, 230, 230)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(60, 60, 60)

    details = [
        ("Company",      campaign.company_name),
        ("Sector",       campaign.sector.title()),
        ("Countries",    ", ".join(campaign.target_countries)),
        ("Client type",  campaign.client_type.upper()),
        ("Goal",         campaign.goal.replace("_", " ").title()),
        ("Horizon",      f"{campaign.horizon_months} months"),
        ("Priority",     campaign.priority.replace("_", " ").title()),
        ("Total budget", f"{int(campaign.total_budget):,} MAD"),
        ("Age range",    f"{campaign.age_min}-{campaign.age_max}"),
        ("Audience",     (campaign.audience_type or "N/A")
                         .replace("_", " ").title()),
    ]

    for label, value in details:
        pdf.set_font("DejaVu", "B", 10)
        pdf.cell(50, 7, f"{label}:", new_x="RIGHT", new_y="LAST")
        pdf.set_font("DejaVu", "", 10)
        pdf.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # ── Section 2: KPI summary ────────────────────────────
    pdf.set_font("DejaVu", "B", 12)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(
        0, 8, "2. Expected Results",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    roi = (
        result.total_revenue / campaign.total_budget * 100
        if campaign.total_budget > 0 else 0
    )

    kpis = [
        ("Total expected leads",   f"{int(result.total_leads):,}"),
        ("Total expected revenue", f"{int(result.total_revenue):,} MAD"),
        ("Estimated ROI",          f"{roi:.0f}%"),
    ]

    for label, value in kpis:
        pdf.set_font("DejaVu", "B", 10)
        pdf.cell(70, 7, f"{label}:", new_x="RIGHT", new_y="LAST")
        pdf.set_font("DejaVu", "", 10)
        pdf.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # ── Section 3: Allocation table ───────────────────────
    pdf.set_font("DejaVu", "B", 12)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(
        0, 8, "3. Budget Allocation",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    # Table header
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("DejaVu", "B", 9)
    pdf.set_text_color(30, 30, 30)

    col_widths = [45, 35, 22, 35, 38]
    headers    = [
        "Channel", "Budget (MAD)", "Share",
        "Leads", "Revenue (MAD)",
    ]

    for i, h in enumerate(headers):
        pdf.cell(
            col_widths[i], 8, h,
            border=1, align="C", fill=True,
            new_x="RIGHT", new_y="LAST",
        )
    pdf.ln()

    # Table rows
    pdf.set_font("DejaVu", "", 9)
    sorted_channels = sorted(
        result.pct_per_channel,
        key=lambda x: -result.pct_per_channel[x],
    )

    for i, ch in enumerate(sorted_channels):
        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(252, 252, 252)
        else:
            pdf.set_fill_color(255, 255, 255)

        row = [
            ch.replace("_", " ").title(),
            f"{int(result.budget_per_channel[ch]):,}",
            f"{result.pct_per_channel[ch]:.1f}%",
            f"{int(result.expected_leads[ch]):,}",
            f"{int(result.expected_revenue[ch]):,}",
        ]
        aligns = ["L", "R", "C", "R", "R"]
        for j, (cell, align) in enumerate(zip(row, aligns)):
            pdf.cell(
                col_widths[j], 7, cell,
                border=1, align=align, fill=fill,
                new_x="RIGHT", new_y="LAST",
            )
        pdf.ln()

    pdf.ln(5)

    # ── Section 4: Explanations ───────────────────────────
    pdf.set_font("DejaVu", "B", 12)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(
        0, 8, "4. Why This Allocation",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    for ch in sorted_channels:
        expl = result.explanations.get(ch, "")

        # Remove special characters that might cause issues
        expl_clean = (
            expl
            .replace("\u2014", "-")   # em dash
            .replace("\u2013", "-")   # en dash
            .replace("\u00b7", ".")   # middle dot
            .replace("\u2019", "'")   # right single quote
            .replace("\u201c", '"')   # left double quote
            .replace("\u201d", '"')   # right double quote
        )

        pdf.set_font("DejaVu", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(
            0, 7,
            f"{ch.replace('_', ' ').title()} "
            f"({result.pct_per_channel[ch]:.1f}%)",
            new_x="LMARGIN", new_y="NEXT",
        )
        pdf.set_font("DejaVu", "", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 6, expl_clean)
        pdf.ln(2)

    pdf.ln(3)

    # ── Section 5: KPIs to monitor ────────────────────────
    pdf.set_font("DejaVu", "B", 12)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(
        0, 8, "5. KPIs to Monitor",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(60, 60, 60)

    for ch in sorted_channels:
        leads   = int(result.expected_leads[ch])
        revenue = int(result.expected_revenue[ch])
        cpl     = round(
            result.budget_per_channel[ch] / leads, 0
        ) if leads > 0 else 0

        line = (
            f"- {ch.replace('_', ' ').title()}: "
            f"target {leads:,} leads | "
            f"CPL <= {int(cpl)} MAD | "
            f"revenue target {revenue:,} MAD"
        )
        pdf.cell(0, 7, line, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)
    pdf.set_font("DejaVu", "", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(
        0, 6,
        "Note: All figures are estimates based on historical benchmarks "
        "and ML predictions. Actual results may vary. "
        "Use these KPIs as targets to monitor campaign performance.",
    )

    return bytes(pdf.output())